# Generated by Django 2.1.3 on 2018-11-26 01:11

import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20181125_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_parcela_individuo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('taxa_juro', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('percentual_entrada', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
        ),
        migrations.RenameField(
            model_name='individuo',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='percentual_entrada',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='taxa_juro',
        ),
        migrations.AddField(
            model_name='consulta',
            name='simulacao',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
