# Generated by Django 2.1.3 on 2018-11-26 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_auto_20181126_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='quantidade_parcelas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(540.0)]),
        ),
    ]
