# Generated by Django 2.1.3 on 2018-11-26 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0006_auto_20181126_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_insercao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
